baseURL = "https://blissos.org/"
title = "BlissOS"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
pagination.pagerSize = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
bgimage = "../assets/images/global/colors.png"
github = "https://github.com/BlissOS"
sitename = "BlissOS"
twitter = "@stayblissful"
description = "Bliss OS For PC"

[params.style]


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.0"
